public static partial class Langs
{
    // TODO: lazy load from file
    // public static class Improbable
    // {
    //     public static IReadOnlyDictionary<string, string[]> PerExtension = new Dictionary<string, string[]>()
    // {
    //    { ".spec", new []{"Python", "RPM Spec", "Ruby"} },
    //    { ".jsp", new []{"Java Server Pages"} },
    //    { ".ascx", new []{"ASP"} },
    //    { ".aug", new []{"Augeas"} },
    //    { ".cql", new []{"SQL"} },
    //    { ".qll", new []{"CodeQL"} },
    //    { ".xquery", new []{"XQuery"} },
    //    { ".rktd", new []{"Racket"} },
    //    { ".muse", new []{"Muse"} },
    //    { ".scpt", new []{"AppleScript"} },
    //    { ".au3", new []{"AutoIt"} },
    //    { ".ecl", new []{"ECLiPSe", "ECL"} },
    //    { ".rsx", new []{"R"} },
    //    { ".axd", new []{"ASP"} },
    //    { ".bib", new []{"BibTeX"} },
    //    { ".el", new []{"Emacs Lisp"} },
    //    { ".zep", new []{"Zephir"} },
    //    { ".mxml", new []{"XML"} },
    //    { ".rbx", new []{"Ruby"} },
    //    { ".ins", new []{"TeX"} },
    //    { ".gf", new []{"Grammatical Framework"} },
    //    { ".gitconfig", new []{"Git Config"} },
    //    { ".pm6", new []{"Raku"} },
    //    { ".matlab", new []{"MATLAB"} },
    //    { ".fth", new []{"Forth"} },
    //    { ".edc", new []{"Edje Data Collection"} },
    //    { ".yasnippet", new []{"YASnippet"} },
    //    { ".p6", new []{"Raku"} },
    //    { ".cirru", new []{"Cirru"} },
    //    { ".gdb", new []{"GDB"} },
    //    { ".emacs.desktop", new []{"Emacs Lisp"} },
    //    { ".tmtheme", new []{"XML Property List"} },
    //    { ".ipp", new []{"C++"} },
    //    { ".props", new []{"XML"} },
    //    { ".yacc", new []{"Yacc"} },
    //    { ".n", new []{"Nemerle", "Roff"} },
    //    { ".lvproj", new []{"LabVIEW"} },
    //    { ".vho", new []{"VHDL"} },
    //    { ".syntax", new []{"YAML"} },
    //    { ".arpa", new []{"DNS Zone"} },
    //    { ".inc", new []{"Motorola 68K Assembly", "C++", "SQL", "Assembly", "PHP", "SourcePawn", "POV-Ray SDL", "Pascal", "Pawn", "NASL", "HTML"} },
    //    { ".hql", new []{"HiveQL"} },
    //    { ".asmx", new []{"ASP"} },
    //    { ".gn", new []{"GN"} },
    //    { ".properties", new []{"INI", "Java Properties"} },
    //    { ".rl", new []{"Ragel"} },
    //    { ".feature", new []{"Gherkin"} },
    //    { ".gbr", new []{"Gerber Image"} },
    //    { ".bbx", new []{"TeX"} },
    //    { ".cps", new []{"Component Pascal"} },
    //    { ".3qt", new []{"Roff Manpage", "Roff"} },
    //    { ".xul", new []{"XML"} },
    //    { ".ipf", new []{"IGOR Pro"} },
    //    { ".oxygene", new []{"Oxygene"} },
    //    { ".vht", new []{"VHDL"} },
    //    { ".sco", new []{"Csound Score"} },
    //    { ".zimpl", new []{"Zimpl"} },
    //    { ".sps", new []{"Scheme"} },
    //    { ".thy", new []{"Isabelle"} },
    //    { ".org", new []{"Org"} },
    //    { ".blade", new []{"Blade"} },
    //    { ".srt", new []{"SRecode Template", "SubRip Text"} },
    //    { ".vhs", new []{"VHDL"} },
    //    { ".texi", new []{"Texinfo"} },
    //    { ".gp", new []{"Gnuplot"} },
    //    { ".pac", new []{"JavaScript"} },
    //    { ".bf", new []{"Brainfuck", "HyPhy"} },
    //    { ".fish", new []{"fish"} },
    //    { ".clixml", new []{"XML"} },
    //    { ".pm", new []{"Raku", "Perl", "X PixMap"} },
    //    { ".zeek", new []{"Zeek"} },
    //    { ".geojson", new []{"JSON"} },
    //    { ".tu", new []{"Turing"} },
    //    { ".i7x", new []{"Inform 7"} },
    //    { ".al", new []{"Perl"} },
    //    { ".xht", new []{"HTML"} },
    //    { ".ma", new []{"Mathematica"} },
    //    { ".phpt", new []{"PHP"} },
    //    { ".ebnf", new []{"EBNF"} },
    //    { ".wsgi", new []{"Python"} },
    //    { ".twig", new []{"Twig"} },
    //    { ".pir", new []{"Parrot Internal Representation"} },
    //    { ".os", new []{"1C Enterprise"} },
    //    { ".prjpcb", new []{"Altium Designer"} },
    //    { ".phtml", new []{"HTML+PHP"} },
    //    { ".mkvi", new []{"TeX"} },
    //    { ".rb", new []{"Ruby"} },
    //    { ".jsonl", new []{"JSON"} },
    //    { ".chem", new []{"Pic"} },
    //    { ".ini", new []{"INI"} },
    //    { ".mdown", new []{"Markdown"} },
    //    { ".ne", new []{"Nearley"} },
    //    { ".vcxproj", new []{"XML"} },
    //    { ".shproj", new []{"XML"} },
    //    { ".asm", new []{"Motorola 68K Assembly", "Assembly"} },
    //    { ".cats", new []{"C"} },
    //    { ".agc", new []{"Apollo Guidance Computer"} },
    //    { ".xml", new []{"XML"} },
    //    { ".bdf", new []{"Glyph Bitmap Distribution Format"} },
    //    { ".gvy", new []{"Groovy"} },
    //    { ".sublime-menu", new []{"JSON with Comments"} },
    //    { ".vue", new []{"Vue"} },
    //    { ".god", new []{"Ruby"} },
    //    { ".scd", new []{"SuperCollider"} },
    //    { ".sra", new []{"PowerBuilder"} },
    //    { ".pbi", new []{"PureBasic"} },
    //    { ".bzl", new []{"Starlark"} },
    //    { ".bsl", new []{"1C Enterprise"} },
    //    { ".vh", new []{"SystemVerilog"} },
    //    { ".gmx", new []{"XML"} },
    //    { ".mms", new []{"Module Management System"} },
    //    { ".tpb", new []{"PLSQL"} },
    //    { ".kicad_pcb", new []{"KiCad Layout"} },
    //    { ".zig", new []{"Zig"} },
    //    { ".rhtml", new []{"RHTML"} },
    //    { ".rest.txt", new []{"reStructuredText"} },
    //    { ".pl", new []{"Raku", "Perl", "Prolog"} },
    //    { ".gql", new []{"GraphQL"} },
    //    { ".svh", new []{"SystemVerilog"} },
    //    { ".eex", new []{"HTML+EEX"} },
    //    { ".yaml-tmlanguage", new []{"YAML"} },
    //    { ".latte", new []{"Latte"} },
    //    { ".xliff", new []{"XML"} },
    //    { ".h", new []{"C++", "Objective-C", "C"} },
    //    { ".for", new []{"Fortran", "Forth", "Formatted"} },
    //    { ".cuh", new []{"Cuda"} },
    //    { ".maxproj", new []{"Max"} },
    //    { ".vhost", new []{"Nginx", "ApacheConf"} },
    //    { ".lektorproject", new []{"INI"} },
    //    { ".tmux", new []{"Shell"} },
    //    { ".druby", new []{"Mirah"} },
    //    { ".adoc", new []{"AsciiDoc"} },
    //    { ".emacs", new []{"Emacs Lisp"} },
    //    { ".9", new []{"Roff Manpage", "Roff"} },
    //    { ".q", new []{"q", "HiveQL"} },
    //    { ".aux", new []{"TeX"} },
    //    { ".txi", new []{"Texinfo"} },
    //    { ".geom", new []{"GLSL"} },
    //    { ".js", new []{"JavaScript"} },
    //    { ".yaml", new []{"YAML"} },
    //    { ".gradle", new []{"Gradle"} },
    //    { ".ado", new []{"Stata"} },
    //    { ".mdpolicy", new []{"XML"} },
    //    { ".yml.mysql", new []{"YAML"} },
    //    { ".cxx-objdump", new []{"Cpp-ObjDump"} },
    //    { ".sld", new []{"Scheme"} },
    //    { ".oxh", new []{"Ox"} },
    //    { ".xql", new []{"XQuery"} },
    //    { "._js", new []{"JavaScript"} },
    //    { ".tcl", new []{"Tcl"} },
    //    { ".wxi", new []{"XML"} },
    //    { ".self", new []{"Self"} },
    //    { ".natvis", new []{"XML"} },
    //    { ".ston", new []{"STON"} },
    //    { ".tmpreferences", new []{"XML Property List"} },
    //    { ".mkdn", new []{"Markdown"} },
    //    { ".em", new []{"EmberScript"} },
    //    { ".mtl", new []{"Wavefront Material"} },
    //    { ".6", new []{"Roff Manpage", "Roff"} },
    //    { ".cjs", new []{"JavaScript"} },
    //    { ".sls", new []{"Scheme", "SaltStack"} },
    //    { ".ld", new []{"Linker Script"} },
    //    { ".mt", new []{"Mathematica"} },
    //    { ".sci", new []{"Scilab"} },
    //    { ".w", new []{"CWeb", "OpenEdge ABL"} },
    //    { ".cc", new []{"C++"} },
    //    { ".jq", new []{"JSONiq"} },
    //    { ".pyi", new []{"Python"} },
    //    { ".asn1", new []{"ASN.1"} },
    //    { ".xq", new []{"XQuery"} },
    //    { ".rdoc", new []{"RDoc"} },
    //    { ".dsp", new []{"Faust", "Microsoft Developer Studio Project"} },
    //    { ".smk", new []{"Python"} },
    //    { ".hcl", new []{"HCL"} },
    //    { ".frg", new []{"GLSL"} },
    //    { ".prw", new []{"xBase"} },
    //    { ".mud", new []{"ZIL"} },
    //    { ".scss", new []{"SCSS"} },
    //    { ".a51", new []{"Assembly"} },
    //    { ".kojo", new []{"Scala"} },
    //    { ".boot", new []{"Clojure"} },
    //    { ".sublime-theme", new []{"JSON with Comments"} },
    //    { ".raw", new []{"Raw token data"} },
    //    { ".numsc", new []{"NumPy"} },
    //    { ".asset", new []{"Unity3D Asset"} },
    //    { ".gnuplot", new []{"Gnuplot"} },
    //    { ".ftl", new []{"FreeMarker"} },
    //    { ".pas", new []{"Pascal"} },
    //    { ".njk", new []{"HTML+Django"} },
    //    { ".shader", new []{"ShaderLab", "GLSL"} },
    //    { ".lex", new []{"Lex"} },
    //    { ".6pm", new []{"Raku"} },
    //    { ".xbm", new []{"X BitMap"} },
    //    { ".graphql", new []{"GraphQL"} },
    //    { ".rss", new []{"XML"} },
    //    { ".rst.txt", new []{"reStructuredText"} },
    //    { ".asc", new []{"AGS Script", "AsciiDoc", "Public Key"} },
    //    { ".go", new []{"Go"} },
    //    { ".tfstate.backup", new []{"JSON"} },
    //    { ".myt", new []{"Myghty"} },
    //    { ".rtf", new []{"Rich Text Format"} },
    //    { ".py", new []{"Python"} },
    //    { ".ch", new []{"xBase", "Charity"} },
    //    { ".wlt", new []{"Mathematica"} },
    //    { ".ux", new []{"XML"} },
    //    { ".njs", new []{"JavaScript"} },
    //    { ".sublime-project", new []{"JSON with Comments"} },
    //    { ".pro", new []{"INI", "IDL", "QMake", "Proguard", "Prolog"} },
    //    { ".nimrod", new []{"Nim"} },
    //    { ".dpatch", new []{"Darcs Patch"} },
    //    { ".rabl", new []{"Ruby"} },
    //    { ".moo", new []{"Mercury", "Moocode"} },
    //    { ".inl", new []{"C++"} },
    //    { ".ccp", new []{"COBOL"} },
    //    { ".xojo_report", new []{"Xojo"} },
    //    { ".mdx", new []{"Markdown"} },
    //    { ".spc", new []{"PLSQL"} },
    //    { ".vssettings", new []{"XML"} },
    //    { ".glade", new []{"XML"} },
    //    { ".ex", new []{"Elixir"} },
    //    { ".csdef", new []{"XML"} },
    //    { ".gco", new []{"G-code"} },
    //    { ".escript", new []{"Erlang"} },
    //    { ".vstemplate", new []{"XML"} },
    //    { ".c-objdump", new []{"C-ObjDump"} },
    //    { ".eclass", new []{"Gentoo Eclass"} },
    //    { ".nr", new []{"Roff"} },
    //    { ".2", new []{"Roff Manpage", "Roff"} },
    //    { ".gtp", new []{"Gerber Image"} },
    //    { ".dlm", new []{"IDL"} },
    //    { ".mkdown", new []{"Markdown"} },
    //    { ".fxml", new []{"XML"} },
    //    { ".psc", new []{"Papyrus"} },
    //    { ".xsp-config", new []{"XPages"} },
    //    { ".ig", new []{"Modula-3"} },
    //    { ".diff", new []{"Diff"} },
    //    { ".asp", new []{"ASP"} },
    //    { ".tmac", new []{"Roff"} },
    //    { ".ceylon", new []{"Ceylon"} },
    //    { ".3in", new []{"Roff Manpage", "Roff"} },
    //    { ".rbi", new []{"Ruby"} },
    //    { ".html", new []{"HTML"} },
    //    { ".oz", new []{"Oz"} },
    //    { ".groovy", new []{"Groovy"} },
    //    { ".pyde", new []{"Python"} },
    //    { ".plsql", new []{"PLSQL"} },
    //    { ".razor", new []{"HTML+Razor"} },
    //    { ".cs", new []{"C#", "Smalltalk"} },
    //    { ".reds", new []{"Red"} },
    //    { ".webmanifest", new []{"JSON"} },
    //    { ".pasm", new []{"Parrot Assembly"} },
    //    { ".epsi", new []{"PostScript"} },
    //    { ".cljx", new []{"Clojure"} },
    //    { ".c++objdump", new []{"Cpp-ObjDump"} },
    //    { ".1m", new []{"Roff Manpage", "Roff"} },
    //    { ".desktop.in", new []{"desktop"} },
    //    { ".mq4", new []{"MQL4"} },
    //    { ".creole", new []{"Creole"} },
    //    { ".vhdl", new []{"VHDL"} },
    //    { ".1in", new []{"Roff Manpage", "Roff"} },
    //    { ".zone", new []{"DNS Zone"} },
    //    { ".zap", new []{"ZAP"} },
    //    { ".rsh", new []{"RenderScript"} },
    //    { ".cljs.hl", new []{"Clojure"} },
    //    { ".geo", new []{"GLSL"} },
    //    { ".cscfg", new []{"XML"} },
    //    { ".blade.php", new []{"Blade"} },
    //    { ".xsp.metadata", new []{"XPages"} },
    //    { ".cgi", new []{"Python", "Perl", "Shell"} },
    //    { ".lidr", new []{"Idris"} },
    //    { ".vhf", new []{"VHDL"} },
    //    { ".lagda", new []{"Literate Agda"} },
    //    { ".sj", new []{"Objective-J"} },
    //    { ".xzap", new []{"ZAP"} },
    //    { ".numpy", new []{"NumPy"} },
    //    { ".pkb", new []{"PLSQL"} },
    //    { ".rego", new []{"Open Policy Agent"} },
    //    { ".glslf", new []{"GLSL"} },
    //    { ".clp", new []{"CLIPS"} },
    //    { ".pkl", new []{"Pickle"} },
    //    { ".ndproj", new []{"XML"} },
    //    { ".fx", new []{"FLUX", "HLSL"} },
    //    { ".ash", new []{"AGS Script"} },
    //    { ".f90", new []{"Fortran"} },
    //    { ".3p", new []{"Roff Manpage", "Roff"} },
    //    { ".tese", new []{"GLSL"} },
    //    { ".rs.in", new []{"Rust"} },
    //    { ".gml", new []{"Game Maker Language", "Gerber Image", "Graph Modeling Language", "XML"} },
    //    { ".angelscript", new []{"AngelScript"} },
    //    { ".sru", new []{"PowerBuilder"} },
    //    { ".frm", new []{"VBA"} },
    //    { ".wiki", new []{"MediaWiki"} },
    //    { ".odin", new []{"Object Data Instance Notation", "Odin"} },
    //    { ".vapi", new []{"Vala"} },
    //    { ".vtt", new []{"WebVTT"} },
    //    { ".scxml", new []{"XML"} },
    //    { ".opa", new []{"Opa"} },
    //    { ".vert", new []{"GLSL"} },
    //    { ".eliomi", new []{"OCaml"} },
    //    { ".4th", new []{"Forth"} },
    //    { ".ttl", new []{"Turtle"} },
    //    { ".vark", new []{"Gosu"} },
    //    { ".kicad_mod", new []{"KiCad Layout"} },
    //    { ".sublime_metrics", new []{"JSON with Comments"} },
    //    { ".pyt", new []{"Python"} },
    //    { ".tac", new []{"Python"} },
    //    { ".nims", new []{"Nim"} },
    //    { ".model.lkml", new []{"LookML"} },
    //    { ".raml", new []{"RAML"} },
    //    { ".db2", new []{"SQLPL"} },
    //    { ".kicad_wks", new []{"KiCad Layout"} },
    //    { ".cnc", new []{"G-code"} },
    //    { ".pic", new []{"Pic"} },
    //    { ".vhi", new []{"VHDL"} },
    //    { ".flux", new []{"FLUX"} },
    //    { ".adb", new []{"Ada"} },
    //    { ".purs", new []{"PureScript"} },
    //    { ".mspec", new []{"Ruby"} },
    //    { ".rexx", new []{"REXX"} },
    //    { ".ring", new []{"Ring"} },
    //    { ".xm", new []{"Logos"} },
    //    { ".storyboard", new []{"XML"} },
    //    { ".gitignore", new []{"Ignore List"} },
    //    { ".logtalk", new []{"Logtalk"} },
    //    { ".cl", new []{"OpenCL", "Cool", "Common Lisp"} },
    //    { ".sh", new []{"Shell"} },
    //    { ".kml", new []{"XML"} },
    //    { ".pbt", new []{"PowerBuilder"} },
    //    { ".sig", new []{"Standard ML"} },
    //    { ".monkey2", new []{"Monkey"} },
    //    { ".mq5", new []{"MQL5"} },
    //    { ".sp", new []{"SourcePawn"} },
    //    { ".mbox", new []{"EML"} },
    //    { ".html.hl", new []{"HTML"} },
    //    { ".b", new []{"Brainfuck", "Limbo"} },
    //    { ".bb", new []{"BitBake", "BlitzBasic"} },
    //    { ".abnf", new []{"ABNF"} },
    //    { ".volt", new []{"Volt"} },
    //    { ".wlk", new []{"Wollok"} },
    //    { ".mustache", new []{"HTML+Django"} },
    //    { ".rei", new []{"Reason"} },
    //    { ".aw", new []{"PHP"} },
    //    { ".csh", new []{"Tcsh"} },
    //    { ".pub", new []{"Public Key"} },
    //    { ".jbuilder", new []{"Ruby"} },
    //    { ".uc", new []{"UnrealScript"} },
    //    { ".osm", new []{"XML"} },
    //    { ".nu", new []{"Nu"} },
    //    { ".sfd", new []{"Spline Font Database"} },
    //    { ".fsproj", new []{"XML"} },
    //    { ".g", new []{"G-code", "GAP"} },
    //    { ".lds", new []{"Linker Script"} },
    //    { ".dfm", new []{"Pascal"} },
    //    { ".eh", new []{"eC"} },
    //    { ".ps1", new []{"PowerShell"} },
    //    { ".axs.erb", new []{"NetLinx+ERB"} },
    //    { ".cmake", new []{"CMake"} },
    //    { ".mjs", new []{"JavaScript"} },
    //    { ".toml", new []{"TOML"} },
    //    { ".gd", new []{"GAP", "GDScript"} },
    //    { ".metal", new []{"Metal"} },
    //    { ".sublime-snippet", new []{"XML"} },
    //    { ".targets", new []{"XML"} },
    //    { ".nqp", new []{"Raku"} },
    //    { ".textile", new []{"Textile"} },
    //    { ".red", new []{"Red"} },
    //    { ".iol", new []{"Jolie"} },
    //    { ".rg", new []{"Rouge"} },
    //    { ".hrl", new []{"Erlang"} },
    //    { ".rktl", new []{"Racket"} },
    //    { ".ol", new []{"Jolie"} },
    //    { ".cls", new []{"Apex", "VBA", "TeX", "OpenEdge ABL", "ObjectScript"} },
    //    { ".pod6", new []{"Pod 6"} },
    //    { ".gms", new []{"GAMS"} },
    //    { ".lhs", new []{"Literate Haskell"} },
    //    { ".iced", new []{"CoffeeScript"} },
    //    { ".lid", new []{"Dylan"} },
    //    { ".workbook", new []{"Markdown"} },
    //    { ".i3", new []{"Modula-3"} },
    //    { ".spin", new []{"Propeller Spin"} },
    //    { ".xpm", new []{"X PixMap"} },
    //    { ".gcode", new []{"G-code"} },
    //    { ".mxt", new []{"Max"} },
    //    { ".tml", new []{"XML"} },
    //    { ".launch", new []{"XML"} },
    //    { ".vhd", new []{"VHDL"} },
    //    { ".sublime-macro", new []{"JSON with Comments"} },
    //    { ".tool", new []{"Shell"} },
    //    { ".ads", new []{"Ada"} },
    //    { ".iss", new []{"Inno Setup"} },
    //    { ".qbs", new []{"QML"} },
    //    { ".php4", new []{"PHP"} },
    //    { ".jsonc", new []{"JSON with Comments"} },
    //    { ".lasso", new []{"Lasso"} },
    //    { ".app.src", new []{"Erlang"} },
    //    { ".applescript", new []{"AppleScript"} },
    //    { ".cw", new []{"Redcode"} },
    //    { ".las", new []{"Lasso"} },
    //    { ".tpl", new []{"Smarty"} },
    //    { ".axi.erb", new []{"NetLinx+ERB"} },
    //    { ".yy", new []{"JSON", "Yacc"} },
    //    { ".sqf", new []{"SQF"} },
    //    { ".zpl", new []{"Zimpl"} },
    //    { ".gbo", new []{"Gerber Image"} },
    //    { ".apl", new []{"APL"} },
    //    { ".hack", new []{"Hack"} },
    //    { ".py3", new []{"Python"} },
    //    { ".f03", new []{"Fortran"} },
    //    { ".tex", new []{"TeX"} },
    //    { ".qml", new []{"QML"} },
    //    { ".vim", new []{"Vim script"} },
    //    { ".scad", new []{"OpenSCAD"} },
    //    { ".watchr", new []{"Ruby"} },
    //    { ".csv", new []{"CSV"} },
    //    { ".mo", new []{"Modelica"} },
    //    { ".jelly", new []{"XML"} },
    //    { ".ijs", new []{"J"} },
    //    { ".mjml", new []{"XML"} },
    //    { ".phps", new []{"PHP"} },
    //    { ".fun", new []{"Standard ML"} },
    //    { ".nproj", new []{"XML"} },
    //    { ".hbs", new []{"Handlebars"} },
    //    { ".kts", new []{"Kotlin"} },
    //    { ".owl", new []{"Web Ontology Language"} },
    //    { ".dats", new []{"ATS"} },
    //    { ".reb", new []{"Rebol"} },
    //    { ".man", new []{"Roff Manpage", "Roff"} },
    //    { ".tesc", new []{"GLSL"} },
    //    { ".tsx", new []{"TSX", "XML"} },
    //    { ".xmi", new []{"XML"} },
    //    { ".cproject", new []{"XML"} },
    //    { ".axml", new []{"XML"} },
    //    { ".psc1", new []{"XML"} },
    //    { ".csproj", new []{"XML"} },
    //    { ".rest", new []{"reStructuredText"} },
    //    { ".sl", new []{"Slash"} },
    //    { ".l", new []{"Common Lisp", "Roff", "PicoLisp", "Lex"} },
    //    { ".duby", new []{"Mirah"} },
    //    { ".nasm", new []{"Assembly"} },
    //    { ".shen", new []{"Shen"} },
    //    { ".krl", new []{"KRL"} },
    //    { ".r3", new []{"Rebol"} },
    //    { ".xaml", new []{"XML"} },
    //    { ".xslt", new []{"XSLT"} },
    //    { ".dylan", new []{"Dylan"} },
    //    { ".opal", new []{"Opal"} },
    //    { ".pcss", new []{"PostCSS"} },
    //    { ".pov", new []{"POV-Ray SDL"} },
    //    { ".vb", new []{"Visual Basic .NET"} },
    //    { ".ps1xml", new []{"XML"} },
    //    { ".rpy", new []{"Ren'Py", "Python"} },
    //    { ".bas", new []{"VBA"} },
    //    { ".gbl", new []{"Gerber Image"} },
    //    { ".nsh", new []{"NSIS"} },
    //    { ".d-objdump", new []{"D-ObjDump"} },
    //    { ".s", new []{"Motorola 68K Assembly", "Unix Assembly"} },
    //    { ".lsp", new []{"NewLisp", "Common Lisp"} },
    //    { ".desktop", new []{"desktop"} },
    //    { ".click", new []{"Click"} },
    //    { ".j", new []{"Jasmin", "Objective-J"} },
    //    { ".filters", new []{"XML"} },
    //    { ".cginc", new []{"HLSL"} },
    //    { ".podspec", new []{"Ruby"} },
    //    { ".gyp", new []{"Python"} },
    //    { ".ily", new []{"LilyPond"} },
    //    { ".mkii", new []{"TeX"} },
    //    { ".wl", new []{"Mathematica"} },
    //    { ".mmk", new []{"Module Management System"} },
    //    { ".nanorc", new []{"nanorc"} },
    //    { ".mediawiki", new []{"MediaWiki"} },
    //    { ".bones", new []{"JavaScript"} },
    //    { ".zsh", new []{"Shell"} },
    //    { ".gpt", new []{"Gerber Image"} },
    //    { ".djs", new []{"Dogescript"} },
    //    { ".tfvars", new []{"HCL"} },
    //    { ".tcsh", new []{"Tcsh"} },
    //    { ".orc", new []{"Csound"} },
    //    { ".anim", new []{"Unity3D Asset"} },
    //    { ".gbp", new []{"Gerber Image"} },
    //    { ".ec", new []{"eC"} },
    //    { ".zs", new []{"ZenScript"} },
    //    { ".gs", new []{"Genie", "Gosu", "JavaScript", "GLSL"} },
    //    { ".dart", new []{"Dart"} },
    //    { ".doh", new []{"Stata"} },
    //    { ".jison", new []{"Jison"} },
    //    { ".mk", new []{"Makefile"} },
    //    { ".cfml", new []{"ColdFusion"} },
    //    { ".qasm", new []{"OpenQASM"} },
    //    { ".axs", new []{"NetLinx"} },
    //    { ".tea", new []{"Tea"} },
    //    { ".patch", new []{"Diff"} },
    //    { ".jsx", new []{"JSX"} },
    //    { ".ui", new []{"XML"} },
    //    { ".jl", new []{"Julia"} },
    //    { ".srw", new []{"PowerBuilder"} },
    //    { ".lua", new []{"Lua"} },
    //    { ".7", new []{"Roff Manpage", "Roff"} },
    //    { ".lslp", new []{"LSL"} },
    //    { ".idc", new []{"C"} },
    //    { ".ashx", new []{"ASP"} },
    //    { ".topojson", new []{"JSON"} },
    //    { ".lfe", new []{"LFE"} },
    //    { ".cl2", new []{"Clojure"} },
    //    { ".view.lkml", new []{"LookML"} },
    //    { ".nimble", new []{"Nim"} },
    //    { ".cpp-objdump", new []{"Cpp-ObjDump"} },
    //    { ".sass", new []{"Sass"} },
    //    { ".no", new []{"Text"} },
    //    { ".jss", new []{"JavaScript"} },
    //    { ".po", new []{"Gettext Catalog"} },
    //    { ".ccproj", new []{"XML"} },
    //    { ".bsv", new []{"Bluespec"} },
    //    { ".ninja", new []{"Ninja"} },
    //    { ".fea", new []{"OpenType Feature File"} },
    //    { ".gshader", new []{"GLSL"} },
    //    { ".ronn", new []{"Markdown"} },
    //    { ".jake", new []{"JavaScript"} },
    //    { ".fcgi", new []{"Python", "PHP", "Perl", "Lua", "Ruby", "Shell"} },
    //    { ".arc", new []{"Arc"} },
    //    { ".udo", new []{"Csound"} },
    //    { ".csl", new []{"XML"} },
    //    { ".sexp", new []{"Common Lisp"} },
    //    { ".perl", new []{"Perl"} },
    //    { ".tpp", new []{"C++"} },
    //    { ".pmod", new []{"Pike"} },
    //    { ".styl", new []{"Stylus"} },
    //    { ".wisp", new []{"wisp"} },
    //    { ".pyw", new []{"Python"} },
    //    { ".rbtbar", new []{"REALbasic"} },
    //    { ".nut", new []{"Squirrel"} },
    //    { ".decls", new []{"BlitzBasic"} },
    //    { ".ly", new []{"LilyPond"} },
    //    { ".brd", new []{"Eagle", "KiCad Legacy Layout"} },
    //    { ".dpr", new []{"Pascal"} },
    //    { ".mat", new []{"Unity3D Asset"} },
    //    { ".tfstate", new []{"JSON"} },
    //    { ".xproj", new []{"XML"} },
    //    { ".rd", new []{"R"} },
    //    { ".hh", new []{"C++", "Hack"} },
    //    { ".rs", new []{"RenderScript", "Rust"} },
    //    { ".rst", new []{"reStructuredText"} },
    //    { ".x68", new []{"Motorola 68K Assembly"} },
    //    { ".cljc", new []{"Clojure"} },
    //    { ".json-tmlanguage", new []{"JSON"} },
    //    { ".fnc", new []{"PLSQL"} },
    //    { ".mu", new []{"mupad"} },
    //    { ".emberscript", new []{"EmberScript"} },
    //    { ".ur", new []{"UrWeb"} },
    //    { ".dae", new []{"COLLADA"} },
    //    { ".mqh", new []{"MQL5", "MQL4"} },
    //    { ".java", new []{"Java"} },
    //    { ".xsd", new []{"XML"} },
    //    { ".snippets", new []{"Vim Snippet"} },
    //    { ".fst", new []{"F*"} },
    //    { ".tl", new []{"Type Language"} },
    //    { ".rbxs", new []{"Lua"} },
    //    { ".xpl", new []{"XProc"} },
    //    { ".auk", new []{"Awk"} },
    //    { ".prc", new []{"PLSQL", "SQL"} },
    //    { ".hlsl", new []{"HLSL"} },
    //    { ".ivy", new []{"XML"} },
    //    { ".hc", new []{"HolyC"} },
    //    { ".gv", new []{"Graphviz (DOT)"} },
    //    { ".p6l", new []{"Raku"} },
    //    { ".sml", new []{"Standard ML"} },
    //    { ".1x", new []{"Roff Manpage", "Roff"} },
    //    { ".xqm", new []{"XQuery"} },
    //    { ".pytb", new []{"Python traceback"} },
    //    { ".re", new []{"C++", "Reason"} },
    //    { ".vala", new []{"Vala"} },
    //    { ".plx", new []{"Perl"} },
    //    { ".sublime-workspace", new []{"JSON with Comments"} },
    //    { ".sparql", new []{"SPARQL"} },
    //    { ".fancypack", new []{"Fancy"} },
    //    { ".p4", new []{"P4"} },
    //    { ".sh.in", new []{"Shell"} },
    //    { ".rno", new []{"Roff", "RUNOFF"} },
    //    { ".maxhelp", new []{"Max"} },
    //    { ".lasso9", new []{"Lasso"} },
    //    { ".sfproj", new []{"XML"} },
    //    { ".regex", new []{"Regular Expression"} },
    //    { ".wsf", new []{"XML"} },
    //    { ".ccxml", new []{"XML"} },
    //    { ".pep", new []{"Pep8"} },
    //    { ".vw", new []{"PLSQL"} },
    //    { ".xc", new []{"XC"} },
    //    { ".prolog", new []{"Prolog"} },
    //    { ".st", new []{"Smalltalk", "HTML"} },
    //    { ".cu", new []{"Cuda"} },
    //    { ".afm", new []{"Adobe Font Metrics"} },
    //    { ".intr", new []{"Dylan"} },
    //    { ".ts", new []{"TypeScript", "XML"} },
    //    { ".befunge", new []{"Befunge"} },
    //    { ".8xk", new []{"TI Program"} },
    //    { ".mcfunction", new []{"mcfunction"} },
    //    { ".fxh", new []{"HLSL"} },
    //    { ".nlogo", new []{"NetLogo"} },
    //    { ".veo", new []{"Verilog"} },
    //    { ".gtpl", new []{"Groovy"} },
    //    { ".elm", new []{"Elm"} },
    //    { ".tla", new []{"TLA"} },
    //    { ".rdf", new []{"XML"} },
    //    { ".iml", new []{"XML"} },
    //    { ".gawk", new []{"Awk"} },
    //    { ".frt", new []{"Forth"} },
    //    { ".dtx", new []{"TeX"} },
    //    { ".vmb", new []{"Vim script"} },
    //    { ".coffee", new []{"CoffeeScript"} },
    //    { ".prisma", new []{"Prisma"} },
    //    { ".fy", new []{"Fancy"} },
    //    { ".glf", new []{"Glyph"} },
    //    { ".oxo", new []{"Ox"} },
    //    { ".yml", new []{"YAML"} },
    //    { ".nearley", new []{"Nearley"} },
    //    { ".fan", new []{"Fantom"} },
    //    { ".jscad", new []{"JavaScript"} },
    //    { ".zmpl", new []{"Zimpl"} },
    //    { ".php5", new []{"PHP"} },
    //    { ".libsonnet", new []{"Jsonnet"} },
    //    { ".hxsl", new []{"Haxe"} },
    //    { ".hsc", new []{"Haskell"} },
    //    { ".grt", new []{"Groovy"} },
    //    { ".fs", new []{"F#", "Forth", "Filterscript", "GLSL"} },
    //    { ".brs", new []{"Brightscript"} },
    //    { ".monkey", new []{"Monkey"} },
    //    { ".cppobjdump", new []{"Cpp-ObjDump"} },
    //    { ".cmake.in", new []{"CMake"} },
    //    { ".aj", new []{"AspectJ"} },
    //    { ".r2", new []{"Rebol"} },
    //    { ".sjs", new []{"JavaScript"} },
    //    { ".es6", new []{"JavaScript"} },
    //    { ".gap", new []{"GAP"} },
    //    { ".rnh", new []{"RUNOFF"} },
    //    { ".5", new []{"Roff Manpage", "Roff"} },
    //    { ".rbfrm", new []{"REALbasic"} },
    //    { ".fsi", new []{"F#"} },
    //    { ".hx", new []{"Haxe"} },
    //    { ".hb", new []{"Harbour"} },
    //    { ".apacheconf", new []{"ApacheConf"} },
    //    { ".ck", new []{"ChucK"} },
    //    { ".ml4", new []{"OCaml"} },
    //    { ".ksh", new []{"Shell"} },
    //    { ".sas", new []{"SAS"} },
    //    { ".ktm", new []{"Kotlin"} },
    //    { ".cxx", new []{"C++"} },
    //    { ".grxml", new []{"XML"} },
    //    { ".3", new []{"Roff Manpage", "Roff"} },
    //    { ".sty", new []{"TeX"} },
    //    { ".pprx", new []{"REXX"} },
    //    { ".mm", new []{"Objective-C++", "XML"} },
    //    { ".mako", new []{"Mako"} },
    //    { ".glsl", new []{"GLSL"} },
    //    { ".rebol", new []{"Rebol"} },
    //    { ".c++", new []{"C++"} },
    //    { ".psm1", new []{"PowerShell"} },
    //    { "._coffee", new []{"CoffeeScript"} },
    //    { ".ecr", new []{"HTML+ECR"} },
    //    { ".smali", new []{"Smali"} },
    //    { ".zil", new []{"ZIL"} },
    //    { ".pt", new []{"XML"} },
    //    { ".roff", new []{"Roff"} },
    //    { ".vbs", new []{"VBScript"} },
    //    { ".dm", new []{"DM"} },
    //    { ".gbs", new []{"Gerber Image"} },
    //    { ".nginxconf", new []{"Nginx"} },
    //    { ".mathematica", new []{"Mathematica"} },
    //    { ".pig", new []{"PigLatin"} },
    //    { ".pgsql", new []{"PLpgSQL"} },
    //    { ".ss", new []{"Scheme"} },
    //    { ".lbx", new []{"TeX"} },
    //    { ".sublime-mousemap", new []{"JSON with Comments"} },
    //    { ".less", new []{"Less"} },
    //    { ".nl", new []{"NewLisp", "NL"} },
    //    { ".gsx", new []{"Gosu"} },
    //    { ".cpy", new []{"COBOL"} },
    //    { ".dita", new []{"XML"} },
    //    { ".mak", new []{"Makefile"} },
    //    { ".jsonld", new []{"JSONLD"} },
    //    { ".di", new []{"D"} },
    //    { ".tps", new []{"PLSQL"} },
    //    { ".xqy", new []{"XQuery"} },
    //    { ".apib", new []{"API Blueprint"} },
    //    { ".rbuild", new []{"Ruby"} },
    //    { ".plb", new []{"PLSQL"} },
    //    { ".boo", new []{"Boo"} },
    //    { ".f08", new []{"Fortran"} },
    //    { ".jflex", new []{"JFlex"} },
    //    { ".ctp", new []{"PHP"} },
    //    { ".cbl", new []{"COBOL"} },
    //    { ".mdwn", new []{"Markdown"} },
    //    { ".udf", new []{"SQL"} },
    //    { ".ssjs", new []{"JavaScript"} },
    //    { ".ditamap", new []{"XML"} },
    //    { ".pyx", new []{"Cython"} },
    //    { ".ct", new []{"XML"} },
    //    { ".gpb", new []{"Gerber Image"} },
    //    { ".cpp", new []{"C++"} },
    //    { ".lean", new []{"Lean"} },
    //    { ".ik", new []{"Ioke"} },
    //    { ".hpp", new []{"C++"} },
    //    { ".ny", new []{"Common Lisp"} },
    //    { ".ino", new []{"C++"} },
    //    { ".thrift", new []{"Thrift"} },
    //    { ".pwn", new []{"Pawn"} },
    //    { ".nc", new []{"nesC"} },
    //    { ".texinfo", new []{"Texinfo"} },
    //    { ".lol", new []{"LOLCODE"} },
    //    { ".es", new []{"JavaScript", "Erlang"} },
    //    { ".pls", new []{"PLSQL"} },
    //    { ".wlua", new []{"Lua"} },
    //    { ".swift", new []{"Swift"} },
    //    { ".ant", new []{"XML"} },
    //    { ".puml", new []{"PlantUML"} },
    //    { ".yyp", new []{"JSON"} },
    //    { ".plist", new []{"XML Property List", "OpenStep Property List"} },
    //    { ".ada", new []{"Ada"} },
    //    { ".css", new []{"CSS"} },
    //    { ".haml", new []{"Haml"} },
    //    { ".io", new []{"Io"} },
    //    { ".ditaval", new []{"XML"} },
    //    { ".mkfile", new []{"Makefile"} },
    //    { ".tab", new []{"SQL"} },
    //    { ".dircolors", new []{"dircolors"} },
    //    { ".php", new []{"PHP", "Hack"} },
    //    { ".tmsnippet", new []{"XML Property List"} },
    //    { ".lpr", new []{"Pascal"} },
    //    { ".lsl", new []{"LSL"} },
    //    { ".bat", new []{"Batchfile"} },
    //    { ".p8", new []{"Lua"} },
    //    { ".resx", new []{"XML"} },
    //    { ".i", new []{"Motorola 68K Assembly", "Assembly", "SWIG"} },
    //    { ".cbx", new []{"TeX"} },
    //    { ".maxpat", new []{"Max"} },
    //    { ".php3", new []{"PHP"} },
    //    { ".als", new []{"Alloy"} },
    //    { ".cocci", new []{"SmPL"} },
    //    { ".sttheme", new []{"XML Property List"} },
    //    { ".m", new []{"MATLAB", "Mathematica", "Mercury", "Objective-C", "Limbo", "M", "MUF"} },
    //    { ".nuspec", new []{"XML"} },
    //    { ".bibtex", new []{"BibTeX"} },
    //    { ".8xp.txt", new []{"TI Program"} },
    //    { ".sbt", new []{"Scala"} },
    //    { ".webidl", new []{"WebIDL"} },
    //    { ".omgrofl", new []{"Omgrofl"} },
    //    { ".ph", new []{"Perl"} },
    //    { ".avsc", new []{"JSON"} },
    //    { ".http", new []{"HTTP"} },
    //    { ".mawk", new []{"Awk"} },
    //    { ".nix", new []{"Nix"} },
    //    { ".xi", new []{"Logos"} },
    //    { ".outjob", new []{"Altium Designer"} },
    //    { ".sv", new []{"SystemVerilog"} },
    //    { ".xs", new []{"XS"} },
    //    { ".pri", new []{"QMake"} },
    //    { ".awk", new []{"Awk"} },
    //    { ".trg", new []{"PLSQL"} },
    //    { ".ql", new []{"CodeQL"} },
    //    { ".4dm", new []{"4D"} },
    //    { ".cjsx", new []{"CoffeeScript"} },
    //    { ".cobol", new []{"COBOL"} },
    //    { ".wxs", new []{"XML"} },
    //    { ".edn", new []{"edn"} },
    //    { ".exs", new []{"Elixir"} },
    //    { ".nbp", new []{"Mathematica"} },
    //    { ".grace", new []{"Grace"} },
    //    { ".8", new []{"Roff Manpage", "Roff"} },
    //    { ".com", new []{"DIGITAL Command Language"} },
    //    { ".x3d", new []{"XML"} },
    //    { ".proj", new []{"XML"} },
    //    { ".ice", new []{"Slice", "JSON"} },
    //    { ".sage", new []{"Sage"} },
    //    { ".vxml", new []{"XML"} },
    //    { ".gaml", new []{"GAML"} },
    //    { ".webapp", new []{"JSON"} },
    //    { ".hlean", new []{"Lean"} },
    //    { ".schdoc", new []{"Altium Designer"} },
    //    { ".cshtml", new []{"HTML+Razor"} },
    //    { ".haml.deface", new []{"Haml"} },
    //    { ".rbw", new []{"Ruby"} },
    //    { ".pck", new []{"PLSQL"} },
    //    { ".mcr", new []{"MAXScript"} },
    //    { ".ddl", new []{"PLSQL", "SQL"} },
    //    { ".hats", new []{"ATS"} },
    //    { ".lmi", new []{"Python"} },
    //    { ".dockerfile", new []{"Dockerfile"} },
    //    { ".jsproj", new []{"XML"} },
    //    { ".do", new []{"Stata"} },
    //    { ".nim", new []{"Nim"} },
    //    { ".toc", new []{"TeX", "World of Warcraft Addon Data"} },
    //    { ".thor", new []{"Ruby"} },
    //    { ".ampl", new []{"AMPL"} },
    //    { ".mg", new []{"Modula-3"} },
    //    { ".sublime-syntax", new []{"YAML"} },
    //    { ".aspx", new []{"ASP"} },
    //    { ".rex", new []{"REXX"} },
    //    { ".jinja2", new []{"HTML+Django"} },
    //    { ".mata", new []{"Stata"} },
    //    { ".xml.dist", new []{"XML"} },
    //    { ".lgt", new []{"Logtalk"} },
    //    { ".ls", new []{"LoomScript", "LiveScript"} },
    //    { ".csd", new []{"Csound Document"} },
    //    { ".scrbl", new []{"Racket"} },
    //    { ".jade", new []{"Pug"} },
    //    { ".ipynb", new []{"Jupyter Notebook"} },
    //    { ".y", new []{"Yacc"} },
    //    { ".parrot", new []{"Parrot"} },
    //    { ".forth", new []{"Forth"} },
    //    { ".erb.deface", new []{"HTML+ERB"} },
    //    { ".txl", new []{"TXL"} },
    //    { ".pug", new []{"Pug"} },
    //    { ".wat", new []{"WebAssembly"} },
    //    { ".bdy", new []{"PLSQL"} },
    //    { ".pod", new []{"Pod 6", "Pod"} },
    //    { ".mir", new []{"YAML"} },
    //    { ".sce", new []{"Scilab"} },
    //    { ".ltx", new []{"TeX"} },
    //    { ".xhtml", new []{"HTML"} },
    //    { ".liquid", new []{"Liquid"} },
    //    { ".xsjslib", new []{"JavaScript"} },
    //    { ".gto", new []{"Gerber Image"} },
    //    { ".cr", new []{"Crystal"} },
    //    { ".builder", new []{"Ruby"} },
    //    { ".moon", new []{"MoonScript"} },
    //    { ".ox", new []{"Ox"} },
    //    { ".sublime-build", new []{"JSON with Comments"} },
    //    { ".eclxml", new []{"ECL"} },
    //    { ".pfa", new []{"PostScript"} },
    //    { ".markdown", new []{"Markdown"} },
    //    { ".nse", new []{"Lua"} },
    //    { ".cp", new []{"C++", "Component Pascal"} },
    //    { ".ahkl", new []{"AutoHotkey"} },
    //    { ".mdoc", new []{"Roff Manpage", "Roff"} },
    //    { ".vrx", new []{"GLSL"} },
    //    { ".factor", new []{"Factor"} },
    //    { ".xib", new []{"XML"} },
    //    { ".sthlp", new []{"Stata"} },
    //    { ".scaml", new []{"Scaml"} },
    //    { ".chpl", new []{"Chapel"} },
    //    { ".fpp", new []{"Fortran"} },
    //    { ".asciidoc", new []{"AsciiDoc"} },
    //    { ".odd", new []{"XML"} },
    //    { ".cy", new []{"Cycript"} },
    //    { ".3m", new []{"Roff Manpage", "Roff"} },
    //    { ".gnu", new []{"Gnuplot"} },
    //    { ".jsfl", new []{"JavaScript"} },
    //    { ".plantuml", new []{"PlantUML"} },
    //    { ".mirah", new []{"Mirah"} },
    //    { ".cob", new []{"COBOL"} },
    //    { ".t", new []{"Turing", "Raku", "Terra", "Perl"} },
    //    { ".hs", new []{"Haskell"} },
    //    { ".darcspatch", new []{"Darcs Patch"} },
    //    { ".8xk.txt", new []{"TI Program"} },
    //    { ".mss", new []{"CartoCSS"} },
    //    { ".xpy", new []{"Python"} },
    //    { ".flex", new []{"JFlex"} },
    //    { ".cake", new []{"C#", "CoffeeScript"} },
    //    { ".pks", new []{"PLSQL"} },
    //    { ".fshader", new []{"GLSL"} },
    //    { ".ruby", new []{"Ruby"} },
    //    { ".pascal", new []{"Pascal"} },
    //    { ".sma", new []{"Pawn"} },
    //    { ".rsc", new []{"Rascal"} },
    //    { ".vba", new []{"VBA", "Vim script"} },
    //    { ".rmd", new []{"RMarkdown"} },
    //    { ".psd1", new []{"PowerShell"} },
    //    { ".rbuistate", new []{"REALbasic"} },
    //    { ".pot", new []{"Gettext Catalog"} },
    //    { ".epj", new []{"Ecere Projects"} },
    //    { ".cson", new []{"CSON"} },
    //    { ".yar", new []{"YARA"} },
    //    { ".hlsli", new []{"HLSL"} },
    //    { ".m3", new []{"Modula-3"} },
    //    { ".dcl", new []{"Clean"} },
    //    { ".pd_lua", new []{"Lua"} },
    //    { ".pike", new []{"Pike"} },
    //    { ".bison", new []{"Bison"} },
    //    { ".p", new []{"OpenEdge ABL", "Gnuplot"} },
    //    { ".erb", new []{"HTML+ERB"} },
    //    { ".eml", new []{"EML"} },
    //    { ".pluginspec", new []{"XML", "Ruby"} },
    //    { ".pp", new []{"Pascal", "Puppet"} },
    //    { ".obj", new []{"Wavefront Object"} },
    //    { ".pxi", new []{"Cython"} },
    //    { ".ihlp", new []{"Stata"} },
    //    { ".pd", new []{"Pure Data"} },
    //    { ".coq", new []{"Coq"} },
    //    { ".plt", new []{"Gnuplot"} },
    //    { ".htm", new []{"HTML"} },
    //    { ".bal", new []{"Ballerina"} },
    //    { ".podsl", new []{"Common Lisp"} },
    //    { ".cljs", new []{"Clojure"} },
    //    { ".ms", new []{"Unix Assembly", "MAXScript", "Roff"} },
    //    { ".meta", new []{"Unity3D Asset"} },
    //    { ".tcc", new []{"C++"} },
    //    { ".pogo", new []{"PogoScript"} },
    //    { ".sagews", new []{"Sage"} },
    //    { ".workflow", new []{"HCL", "XML"} },
    //    { ".smt", new []{"SMT"} },
    //    { ".flf", new []{"FIGlet Font"} },
    //    { ".yara", new []{"YARA"} },
    //    { ".numpyw", new []{"NumPy"} },
    //    { ".hs-boot", new []{"Haskell"} },
    //    { ".cljscm", new []{"Clojure"} },
    //    { ".rbbas", new []{"REALbasic"} },
    //    { ".stan", new []{"Stan"} },
    //    { ".lasso8", new []{"Lasso"} },
    //    { ".gni", new []{"GN"} },
    //    { ".ml", new []{"Standard ML", "OCaml"} },
    //    { ".sublime-settings", new []{"JSON with Comments"} },
    //    { ".jisonlex", new []{"Jison Lex"} },
    //    { ".snip", new []{"Vim Snippet"} },
    //    { ".pxd", new []{"Cython"} },
    //    { ".gts", new []{"Gerber Image"} },
    //    { ".mtml", new []{"MTML"} },
    //    { ".ahk", new []{"AutoHotkey"} },
    //    { ".capnp", new []{"Cap'n Proto"} },
    //    { ".xacro", new []{"XML"} },
    //    { ".pkgproj", new []{"XML"} },
    //    { ".mask", new []{"Mask", "Unity3D Asset"} },
    //    { ".nsi", new []{"NSIS"} },
    //    { ".hxx", new []{"C++"} },
    //    { ".hhi", new []{"Hack"} },
    //    { ".json5", new []{"JSON5"} },
    //    { ".p6m", new []{"Raku"} },
    //    { ".hic", new []{"Clojure"} },
    //    { ".wsdl", new []{"XML"} },
    //    { ".json", new []{"JSON"} },
    //    { ".lookml", new []{"LookML"} },
    //    { ".golo", new []{"Golo"} },
    //    { ".graphqls", new []{"GraphQL"} },
    //    { ".glslv", new []{"GLSL"} },
    //    { ".chs", new []{"C2hs Haskell"} },
    //    { ".uno", new []{"Uno"} },
    //    { ".g4", new []{"ANTLR"} },
    //    { ".vbhtml", new []{"Visual Basic .NET"} },
    //    { ".mao", new []{"Mako"} },
    //    { ".mll", new []{"OCaml"} },
    //    { ".slim", new []{"Slim"} },
    //    { ".asn", new []{"ASN.1"} },
    //    { ".frag", new []{"JavaScript", "GLSL"} },
    //    { ".c++-objdump", new []{"Cpp-ObjDump"} },
    //    { ".kt", new []{"Kotlin"} },
    //    { ".eam.fs", new []{"Formatted"} },
    //    { ".dot", new []{"Graphviz (DOT)"} },
    //    { ".yrl", new []{"Erlang"} },
    //    { ".fr", new []{"Text", "Forth", "Frege"} },
    //    { ".sublime-completions", new []{"JSON with Comments"} },
    //    { ".asd", new []{"Common Lisp"} },
    //    { ".sed", new []{"sed"} },
    //    { ".cabal", new []{"Cabal Config"} },
    //    { ".sch", new []{"Scheme", "KiCad Schematic", "Eagle", "XML"} },
    //    { ".d", new []{"Makefile", "DTrace", "D"} },
    //    { ".adp", new []{"Tcl"} },
    //    { ".xrl", new []{"Erlang"} },
    //    { ".cfc", new []{"ColdFusion CFC"} },
    //    { ".as", new []{"AngelScript", "ActionScript"} },
    //    { ".hy", new []{"Hy"} },
    //    { ".xsl", new []{"XSLT"} },
    //    { ".rockspec", new []{"Lua"} },
    //    { ".vsh", new []{"GLSL"} },
    //    { ".xlf", new []{"XML"} },
    //    { ".ps", new []{"PostScript"} },
    //    { ".vcl", new []{"VCL"} },
    //    { ".cdf", new []{"Mathematica"} },
    //    { ".sats", new []{"ATS"} },
    //    { ".8xp", new []{"TI Program"} },
    //    { ".6pl", new []{"Raku"} },
    //    { ".nit", new []{"Nit"} },
    //    { ".weechatlog", new []{"IRC log"} },
    //    { ".f95", new []{"Fortran"} },
    //    { ".viw", new []{"SQL"} },
    //    { ".ni", new []{"Inform 7"} },
    //    { ".f77", new []{"Fortran"} },
    //    { ".sublime-commands", new []{"JSON with Comments"} },
    //    { ".objdump", new []{"ObjDump"} },
    //    { ".dyalog", new []{"APL"} },
    //    { ".gko", new []{"Gerber Image"} },
    //    { ".kit", new []{"Kit"} },
    //    { ".pb", new []{"PureBasic"} },
    //    { ".pcbdoc", new []{"Altium Designer"} },
    //    { "._ls", new []{"LiveScript"} },
    //    { ".nb", new []{"Text", "Mathematica"} },
    //    { ".fp", new []{"GLSL"} },
    //    { ".3x", new []{"Roff Manpage", "Roff"} },
    //    { ".xojo_code", new []{"Xojo"} },
    //    { ".adml", new []{"XML"} },
    //    { ".erl", new []{"Erlang"} },
    //    { ".jinja", new []{"HTML+Django"} },
    //    { ".smt2", new []{"SMT"} },
    //    { ".robot", new []{"RobotFramework"} },
    //    { ".soy", new []{"Closure Templates"} },
    //    { ".urdf", new []{"XML"} },
    //    { ".cfm", new []{"ColdFusion"} },
    //    { ".x10", new []{"X10"} },
    //    { ".dwl", new []{"DataWeave"} },
    //    { ".prefab", new []{"Unity3D Asset"} },
    //    { ".gst", new []{"Gosu"} },
    //    { ".js.erb", new []{"JavaScript+ERB"} },
    //    { ".idr", new []{"Idris"} },
    //    { ".nim.cfg", new []{"Nim"} },
    //    { ".xproc", new []{"XProc"} },
    //    { ".vsixmanifest", new []{"XML"} },
    //    { ".pde", new []{"Processing"} },
    //    { ".c", new []{"C"} },
    //    { ".admx", new []{"XML"} },
    //    { ".eye", new []{"Ruby"} },
    //    { ".proto", new []{"Protocol Buffer"} },
    //    { ".sublime_session", new []{"JSON with Comments"} },
    //    { ".sc", new []{"SuperCollider", "Scala"} },
    //    { ".clw", new []{"Clarion"} },
    //    { ".dll.config", new []{"XML"} },
    //    { ".vbproj", new []{"XML"} },
    //    { ".command", new []{"Shell"} },
    //    { ".reg", new []{"Windows Registry Entries"} },
    //    { ".me", new []{"Roff"} },
    //    { ".ru", new []{"Ruby"} },
    //    { ".mrc", new []{"mIRC Script"} },
    //    { ".v", new []{"V", "Verilog", "Coq"} },
    //    { ".vhw", new []{"VHDL"} },
    //    { ".pat", new []{"Max"} },
    //    { ".rq", new []{"SPARQL"} },
    //    { ".abap", new []{"ABAP"} },
    //    { ".bmx", new []{"BlitzMax"} },
    //    { ".tm", new []{"Tcl"} },
    //    { ".cmd", new []{"Batchfile"} },
    //    { ".mli", new []{"OCaml"} },
    //    { ".riot", new []{"Riot"} },
    //    { ".opencl", new []{"OpenCL"} },
    //    { ".md", new []{"Markdown", "GCC Machine Description"} },
    //    { ".sublime-keymap", new []{"JSON with Comments"} },
    //    { ".clj", new []{"Clojure"} },
    //    { ".irclog", new []{"IRC log"} },
    //    { ".e", new []{"Eiffel", "E"} },
    //    { ".gsp", new []{"Groovy Server Pages"} },
    //    { ".jsm", new []{"JavaScript"} },
    //    { ".1", new []{"Roff Manpage", "Roff"} },
    //    { ".xspec", new []{"XML"} },
    //    { ".urs", new []{"UrWeb"} },
    //    { ".wixproj", new []{"XML"} },
    //    { ".eb", new []{"Easybuild"} },
    //    { ".hqf", new []{"SQF"} },
    //    { ".ejs", new []{"EJS"} },
    //    { ".conllu", new []{"CoNLL-U"} },
    //    { ".jsb", new []{"JavaScript"} },
    //    { ".ncl", new []{"Text", "NCL", "XML"} },
    //    { ".vshader", new []{"GLSL"} },
    //    { ".x", new []{"DirectX 3D File", "Logos", "RPC", "Linker Script"} },
    //    { ".r", new []{"R", "Rebol"} },
    //    { ".srdf", new []{"XML"} },
    //    { ".mcmeta", new []{"JSON"} },
    //    { ".har", new []{"JSON"} },
    //    { ".matah", new []{"Stata"} },
    //    { ".nf", new []{"Nextflow"} },
    //    { ".hxml", new []{"HXML"} },
    //    { ".pl6", new []{"Raku"} },
    //    { ".postcss", new []{"PostCSS"} },
    //    { ".rake", new []{"Ruby"} },
    //    { ".depproj", new []{"XML"} },
    //    { ".mly", new []{"OCaml"} },
    //    { ".rkt", new []{"Racket"} },
    //    { ".conll", new []{"CoNLL-U"} },
    //    { ".asax", new []{"ASP"} },
    //    { ".dyl", new []{"Dylan"} },
    //    { ".lisp", new []{"NewLisp", "Common Lisp"} },
    //    { ".dotsettings", new []{"XML"} },
    //    { ".svelte", new []{"Svelte"} },
    //    { ".eps", new []{"PostScript"} },
    //    { ".wast", new []{"WebAssembly"} },
    //    { ".sh-session", new []{"ShellSession"} },
    //    { ".reek", new []{"YAML"} },
    //    { ".gtl", new []{"Gerber Image"} },
    //    { ".axi", new []{"NetLinx"} },
    //    { ".fsx", new []{"F#"} },
    //    { ".minid", new []{"MiniD"} },
    //    { ".wdl", new []{"wdl"} },
    //    { ".bash", new []{"Shell"} },
    //    { ".f", new []{"Fortran", "Forth", "Filebench WML"} },
    //    { ".prg", new []{"xBase"} },
    //    { ".rviz", new []{"YAML"} },
    //    { ".upc", new []{"Unified Parallel C"} },
    //    { ".jsonnet", new []{"Jsonnet"} },
    //    { ".ll", new []{"LLVM"} },
    //    { ".eliom", new []{"OCaml"} },
    //    { ".plot", new []{"Gnuplot"} },
    //    { ".svg", new []{"SVG"} },
    //    { ".fsh", new []{"GLSL"} },
    //    { ".pan", new []{"Pan"} },
    //    { ".rbres", new []{"REALbasic"} },
    //    { ".yaml.sed", new []{"YAML"} },
    //    { ".tmlanguage", new []{"XML Property List"} },
    //    { ".dhall", new []{"Dhall"} },
    //    { ".litcoffee", new []{"Literate CoffeeScript"} },
    //    { ".cwl", new []{"Common Workflow Language"} },
    //    { ".icl", new []{"Clean"} },
    //    { ".zcml", new []{"XML"} },
    //    { ".ooc", new []{"ooc"} },
    //    { ".make", new []{"Makefile"} },
    //    { ".sss", new []{"SugarSS"} },
    //    { ".pyp", new []{"Python"} },
    //    { ".yap", new []{"Prolog"} },
    //    { ".tf", new []{"HCL"} },
    //    { ".unity", new []{"Unity3D Asset"} },
    //    { ".regexp", new []{"Regular Expression"} },
    //    { ".snippet", new []{"Vim Snippet"} },
    //    { ".gltf", new []{"JSON"} },
    //    { ".rbmnu", new []{"REALbasic"} },
    //    { ".3pm", new []{"Roff Manpage", "Roff"} },
    //    { ".xojo_script", new []{"Xojo"} },
    //    { ".xojo_menu", new []{"Xojo"} },
    //    { ".kid", new []{"Genshi"} },
    //    { ".prefs", new []{"INI"} },
    //    { ".mod", new []{"AMPL", "Modula-2", "Linux Kernel Module", "XML"} },
    //    { ".gemspec", new []{"Ruby"} },
    //    { ".psgi", new []{"Perl"} },
    //    { ".tst", new []{"GAP", "Scilab"} },
    //    { ".xojo_toolbar", new []{"Xojo"} },
    //    { ".txt", new []{"Text"} },
    //    { ".iuml", new []{"PlantUML"} },
    //    { ".frx", new []{"VBA"} },
    //    { ".nawk", new []{"Awk"} },
    //    { ".eq", new []{"EQ"} },
    //    { ".dof", new []{"INI"} },
    //    { ".4", new []{"Roff Manpage", "Roff"} },
    //    { ".gypi", new []{"Python"} },
    //    { ".gi", new []{"GAP"} },
    //    { ".mysql", new []{"SQL"} },
    //    { ".ebuild", new []{"Gentoo Ebuild"} },
    //    { ".gdbinit", new []{"GDB"} },
    //    { ".marko", new []{"Marko"} },
    //    { ".bats", new []{"Shell"} },
    //    { ".xojo_window", new []{"Xojo"} },
    //    { ".xtend", new []{"Xtend"} },
    //    { ".handlebars", new []{"Handlebars"} },
    //    { ".h++", new []{"C++"} },
    //    { ".m4", new []{"M4", "M4Sugar"} },
    //    { ".sql", new []{"PLSQL", "SQL", "TSQL", "PLpgSQL", "SQLPL"} },
    //    { ".nasl", new []{"NASL"} },
    //    { ".scm", new []{"Scheme"} },
    //    { ".pony", new []{"Pony"} },
    //    { ".scala", new []{"Scala"} },
    //    { ".mkd", new []{"Markdown"} },
    //    { ".builds", new []{"XML"} },
    //    { ".muf", new []{"MUF"} },
    //    { ".bro", new []{"Zeek"} },
    //    { ".cfg", new []{"INI", "HAProxy"} },
    //    { ".yang", new []{"YANG"} },
    //    { ".wxl", new []{"XML"} },
    //    { ".agda", new []{"Agda"} },
    //    { ".mumps", new []{"M"} },
    //    { ".xsjs", new []{"JavaScript"} },
    //    { ".tmcommand", new []{"XML Property List"} },
    //    { ".mlir", new []{"MLIR"} },
    //    { ".asy", new []{"LTspice Symbol", "Asymptote"} },
    //    { ".csx", new []{"C#"} },
    //    { ".mkiv", new []{"TeX"} },
    // };
    // }
}
